# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"

In [5]:
s= "Hi there Sam"
s=s.split()                    
print(s);


['Hi', 'there', 'Sam']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
planet = "Earth"
diameter = 12742
print('the diameter of {} is {} kilometers.'.format(planet,diameter))


the diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
import numpy as np
array=np.zeros(10)
print("an array of 10 zeros:")
print(array)

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
array = np.ones(10)*5
print("an array of 10 fives:")
print (array)

an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,35,2)
print("array of all even integer from 20 to 35")
print(array)


array of all even integer from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr = np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd


In [17]:
import pandas as pd
import numpy as np

arrayA=['M', 'K']
arrayB=['1', '2']
arrayC=['M','Y']
pd.DataFrame(np.array([arrayA, arrayB, arrayC]),columns=["AA", "NN"])

AA NN
0  M  K
1  1  2
2  M  Y

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
from datetime import date as date_n
def number_of_days(date_1,date_2):
    return(date_2-date_1).days
date_1=date_n(2023,1,1)
date_2=date_n(2023,2,10)
print("number of days between the given dates are:",number_of_days(date_1,date_2),"days")

number of days between the given dates are: 40 days


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
import pandas as pd
list=[['aaa',22],['bbb',25],['ccc',24]]
df=pd.DataFrame(list,columns=['tag','number'])
print(df)


   tag  number
0  aaa      22
1  bbb      25
2  ccc      24
